# Generated by Django 4.0.2 on 2022-02-08 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaehora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_loja', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=11)),
                ('telefone_loja', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.AddField(
            model_name='compras',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.loja'),
        ),
        migrations.AddField(
            model_name='compras',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.produto'),
        ),
        migrations.AddField(
            model_name='compras',
            name='usu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.usuario'),
        ),
    ]
