# Generated by Django 4.0.2 on 2022-02-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_compras_loja_produto_usuario_delete_todo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='nome_prod',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
